name: Test workflow

on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - run: echo foo
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: DL artifacts
        uses: actions/download-artifact@master
        with:
          name: hello-world
          path: artifact
      - name: ls
        run: ls artifact -ltr
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 12.x
          - 10.x
    steps:
    - env:
        JOB_CTX: ${{ toJson(github) }}
      run: echo $JOB_CTX
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: Create dummy artifact
      if: matrix.node_version == '12.x'
      run: echo world > hello.txt
    - name: Upload artifacts
      if: matrix.node_version == '12.x'
      uses: actions/upload-artifact@master
      with:
        name: hello-world
        path: hello.txt
