name: Test workflow

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    needs:
      - build
      - lint
    steps:
      - name: Foo
        run: echo Foo
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Make artifact dir
      run: mkdir -p artifacts/${{ matrix.os }}
    - name: Create dummy artifact
      run: echo hello > artifacts/${{ matrix.os }}/world.txt
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Artifact - ${{ matrix.os }}
        path: artifacts/${{ matrix.os }}/world.txt
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Do a lint
      run: echo I am linting
