name: Test workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - &oobs ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 50
        submodules: true
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
  lint:
    runs-on: *oobs
    steps:
    - uses: actions/checkout@master
    - name: Do a lint
      run: echo I am linting
