name: Test workflow

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: DL artifacts
        uses: actions/download-artifact@master
        with:
          name: hello-world
          path: artifact
      - name: ls
        run: ls artifact -ltr
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Create dummy artifact
      run: echo world > hello.txt
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: hello-world
        path: hello.txt
