name: Test workflow

on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - run: echo foo
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: DL artifacts
        uses: actions/download-artifact@master
        with:
          name: hello-world
          path: artifact
      - name: ls
        run: ls artifact -ltr
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 12.x
          - 10.x
        os:
          - ubuntu-latest
          - macOS-latest
    steps:
    - uses: actions/checkout@master
      if: matrix.os == 'ubuntu-latest'
      with:
        fetch-depth: 1
    - name: Create dummy artifact
      if: matrix.os == 'ubuntu-latest'
      run: echo world > hello.txt
    - name: Upload artifacts
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@master
      with:
        name: hello-world
        path: hello.txt
